---
sidebar: sidebar 
permalink: fsx/configuration-analysis-fsx.html 
keywords: configuration issues, issues, improve, analyze, storage configuration, recommendation, recommendations 
summary: 適切に設計されたダッシュボードは、FSx for ONTAP ファイルシステムの構成を定期的に分析し、構成上の問題がないかどうかを確認します。 
---
= Amazon FSx for NetApp ONTAP の構成分析
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp Console のよく設計されたダッシュボードは、ストレージシステムの構成を定期的に分析し、Amazon FSx for NetApp ONTAP ファイルシステムに構成上の問題がないかどうかを判断します。問題が検出されると、ダッシュボードには問題の内容が表示され、ストレージシステムが最高のパフォーマンス、対費用効果の高い効率、およびベストプラクティスへの準拠を達成するために何を変更する必要があるかが説明されます。

主な機能は次のとおりです：

* 日次構成分析
* NetApp ONTAPストレージシステムおよびパートナーストレージプロバイダーに対する自動ベストプラクティス検証
* プロアクティブな可観測性
* 洞察から行動へ


未解決のディレクティブ（<stdin>）- include::well-architected-workloads.adoc[]



[[analysis-requirements]]
== 分析要件

ファイルシステムを完全に分析するには、以下の手順を実行する必要があります。

* link:https://docs.netapp.com/us-en/console-setup-admin/concept-agent-install-options.html#agent-console-deploy["NetApp Console エージェントのデプロイ"^]またはlink:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["リンクを関連付ける"^]を使用して、ファイルシステムとNetApp Console間の接続を設定します。
* AWS アカウントで_表示、計画、分析_の権限を付与してください。
+
link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["AWS アカウントに権限を付与する方法を説明します"^]



未解決のディレクティブ（<stdin>）- include::fsx-configurations.adoc[]

.次の手順
link:improve-configurations-fsx.html["適切に設計された FSx for ONTAP ファイルシステム構成を実装する"]
