---
sidebar: sidebar 
permalink: fsx/configuration-analysis-fsx.html 
keywords: configuration issues, issues, improve, analyze, storage configuration, recommendation, recommendations 
summary: NetApp Console は、ストレージシステムの構成を定期的に分析し、構成上の問題がないかどうかを判断します。 
---
= Amazon FSx for NetApp ONTAP の構成分析
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp Console は、ストレージシステムの構成を定期的に分析し、構成上の問題がないかどうかを判断します。問題が見つかった場合、NetApp Console は問題点を表示し、ストレージシステムが最高のパフォーマンス、コスト効率、およびベストプラクティスへの準拠を達成するために何を変更する必要があるかを説明します。

主な機能は次のとおりです：

* 日次構成分析
* NetApp ONTAPストレージシステムおよびパートナーストレージプロバイダーに対する自動ベストプラクティス検証
* プロアクティブな可観測性
* 洞察から行動へ




[[how-it-works]]
== 仕組み

Workload Factory は、Amazon FSx for NetApp ONTAP ファイルシステムの導入環境で実行されているワークロードを毎日分析します。この分析により、適切に設計されたステータス、インサイト、および推奨事項が提供されます。

日々の分析が完了すると、デプロイメントのWell-architectedダッシュボードに、構成が「最適化済み」または「最適化されていない」として表示されます。総合的な最適化スコア、カテゴリ別の設定上の問題点、および設定上の問題点と推奨事項の一覧が表示されます。設定に関する問題については、推奨事項をご確認ください。一部の問題はWorkload Factoryによって自動的に修正できますが、その他の問題は手動での介入が必要です。この場合、Workload Factoryは、推奨される変更を実装するのに役立つ詳細な手順を提供します。

ご自身の環境に適用されない構成の分析は無視することができます。これにより、不要なアラートや不正確な最適化結果を回避できます。特定の構成分析を無視すると、Workload Factory ではその構成が全体の最適化スコアに含められません。



[[why-it-matters]]
== 重要な理由

Workload Factoryは、継続的な評価と推奨事項、および修復策を組み合わせることで、大規模なストレージ、データベース、およびVMware環境にベストプラクティスを適用します。Workload Factoryコンソールで適用される自動修正により、人的ミスが削減され、統一された管理が確保され、ワークロードインフラストラクチャ全体でパフォーマンスと信頼性が維持されます。



[[analysis-requirements]]
== 分析要件

ファイルシステムを完全に分析するには、以下の手順を実行する必要があります。

* link:https://docs.netapp.com/us-en/console-setup-admin/concept-agent-install-options.html#agent-console-deploy["NetApp Console エージェントのデプロイ"^] または link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["リンクを関連付ける"^]。コンソールエージェントとリンク接続により、NetApp Console はデータ保護やパフォーマンスなど、すべてのファイルシステム構成を分析します。
* AWS アカウントで_表示、計画、分析_の権限を付与してください。
+
link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["AWS アカウントに権限を付与する方法を説明します"^]





[[best-practices-and-recommendations-for-storage-workloads]]
== ストレージワークロードに関するベストプラクティスと推奨事項

Workload Factory は、ONTAP のベストプラクティスと AWS Well-Architected Framework に照らしてストレージ構成を評価します。この評価では、改善点や修正点も提言します。

適切に設計された分析では、構成をフレームワークの次の柱に分類します：_信頼性_、_セキュリティ_、_運用効率_、_コスト最適化_、および_パフォーマンス効率_。



[[reliability]]
=== 信頼性

信頼性とは、障害が発生した場合でも、ワークロードが意図された機能を正確かつ一貫して実行することを保証するものです。

* *ボリュームバックアップをスケジュールする*
+
ボリュームのバックアップは、データ保持とコンプライアンスのニーズをサポートするのに役立ちます。ボリュームバックアップを使用して、データの自動バックアップと保持を設定します。

* *ローカルスナップショットのスケジュール設定*
+
効率的なバックアップと迅速な復元のために、ローカルスナップショットをスケジュール設定しましょう。スナップショットは、ボリュームの瞬時のポイントインタイムイメージです。

* *リージョン間レプリケーション*
+
クロスリージョンレプリケーションにより、データが別の AWS リージョンにレプリケートされ、データの耐久性と可用性が向上します。Workload Factory では、災害復旧とコンプライアンスを支援するために、クロスリージョンレプリケーションを設定することを推奨しています。

* *データレプリケーションの設定*
+
データの信頼性を高めるために、データを同一リージョン内または別リージョン内のFSx for ONTAPファイルシステムに複製することができます。ファイルシステム間での移行、災害復旧、および長期保存をサポートするために、データレプリケーションを設定します。

* *SSD容量のしきい値を上げる*
+
SSDストレージ層の容量は、使用率が80%を超えないようにしてください。これは、キャパシティプールストレージ層へのデータの読み書きに影響を与え、ファイルシステムのスループット容量にも影響を与える可能性があります。容量が不足すると、データボリュームは読み取り専用になります。新しいデータを書き込もうとするサービスも失敗します。

* *データの信頼性を確保するためにラベルを一致させる*
+
データの信頼性を確保するためには、ソースボリュームのSnapshotポリシーラベルとレプリケーションポリシーラベルが一致している必要があります。

* *ファイル容量のしきい値を上げる*
+
ボリューム容量制限に達しないように、ファイル容量のしきい値を引き上げるべきです。ファイル容量（iノード）が不足しているため、ボリュームへの追加データの書き込みができません。Workload Factoryは、ファイル容量の使用率を80%未満に維持することを推奨しています。ボリューム内に新しいファイルを作成するには、利用可能なファイル容量が必要です。





[[security]]
=== セキュリティ

セキュリティは、リスク評価と軽減戦略を通じて、データ、システム、資産を保護することを重視します。

* *ARP/AIを有効にする*
+
NetApp Autonomous Ransomware Protection with AI（ARP/AI）は、ボリュームをランサムウェアの脅威から保護するのに役立ちます。Workload Factory では、すべてのボリュームに対して ARP/AI を有効にすることをお勧めします。

* *ボリュームへの不正アクセス*
+
iSCSIを使用してアプリケーションデータを提供するボリュームは、同時にNASアクセスを許可すべきではありません。Workload Factoryは、iSCSIボリュームが他のプロトコルを使用しないよう制限することを推奨します。





[[operational-excellence]]
=== 運用の卓越性

運用上の卓越性とは、最適なアーキテクチャとビジネス価値を提供することに重点を置くものです。

* *自動容量管理を有効にする*
+
SSD 階層がしきい値を超えないように定期的に確保するには、自動容量管理を有効にする必要があります。

* *ボリューム容量使用率のしきい値*
+
Workload Factoryは、ボリューム容量の利用率が継続的に80%を超えないようにすることを推奨しています。これは、アプリケーションへのデータの読み書きに影響を与える可能性があります。ボリューム容量の増加は、手動またはボリュームの自動拡張機能を使用して自動的に行うことができます。

* *ボリューム使用率がほぼ満杯です*
+
ボリュームの容量がほぼ満杯に近づいた場合、NetApp Workload Factoryは、アプリケーションの潜在的な中断を回避するために、ボリューム容量を増やすための対策を講じることを推奨します。

* *キャッシュ関係の書き込みモード*
+
最適なパフォーマンスを実現するために、Workload Factoryはワークロードに最適なキャッシュ関係書き込みモードを推奨します。ライトアラウンドモードは、小さなファイルを扱う読み込み中心のワークロードにおいて優れたパフォーマンスを発揮する一方、ライトバックモードは、大きなファイルを扱う書き込み中心のワークロードにおいて優れたパフォーマンスを発揮します。

* *キャッシュボリュームのサイズを最適化*
+
Workload Factory では、最適なサイズを維持し、ホットデータにキャッシュを集中させて効率を最大限に高めるために、ボリュームの自動サイズ調整とキャッシュボリュームのスクラブを有効にすることを推奨しています。

* *Storage VM論理レポート*
+
Workload Factory では、ボリュームレベルでのストレージ使用状況をより適切に把握できるように、ストレージ VM のデフォルトのレポート設定を論理に設定することをお勧めします。





[[cost-optimization]]
=== コスト最適化

コストの最適化により、コストを低く抑えながらビジネスの価値を最大限に高めることができます。

* *コールドデータを階層化することでTCOを最適化*
+
SSDストレージ階層の利用率を削減するために、コールドデータ階層化を有効にしてください。Workload Factoryは、すべてのボリュームに階層化ポリシーを適用することを推奨しています。FSx for ONTAPは、データを継続的にスキャンして、使用頻度の低いデータを検出し、中断することなく容量ストレージプール層に移動します。

* *ストレージ効率を有効にする*
+
ストレージ効率化機能（コンパクション、圧縮、重複排除）を有効にすることで、ストレージ利用率を最適化し、SSDティアのコストを削減します。

* *不要なスナップショットおよびバックアップの削除*
+
不要になったスナップショットやバックアップは、コスト削減のため削除する必要があります。

* *非アクティブなブロックデバイス*
+
ブロックデバイスが7日間使用されなかった場合、Workload Factoryはブロックデバイスデータをアーカイブするか、未使用のブロックデバイスを削除してコストを削減することを推奨します。

* *SSD容量の使用率が低い*
+
SSDの容量が十分に活用されていないと、不必要なコストが発生します。Workload Factoryは、SSDティアの容量を削減しつつ、現在使用している容量より20%高い空き容量バッファを維持することを推奨しています。縮小操作には数時間から数日かかる場合があり、その間、システムは他のファイルシステム操作をサポートしません。

* *非アクティブなNASボリューム*
+
構成分析では、アクティブに使用されていないNASボリュームを特定し、コスト削減のためにボリュームを削除またはアーカイブすることを推奨します。



.次の手順
link:fsx/improve-configurations-fsx.html["適切に設計された FSx for ONTAP ファイルシステム構成を実装する"]
