---
sidebar: sidebar 
permalink: cvo/configuration-analysis-cvo.html 
keywords: Cloud Volumes ONTAP, configuration issues, issues, improve, analyze, storage configuration, recommendation, recommendations 
summary: NetApp Console は、ストレージシステムの構成を毎日分析し、構成上の問題がないかどうかを判断します。 
---
= Cloud Volumes ONTAP の構成分析
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp Console は、ストレージシステムの構成を定期的に分析し、構成上の問題がないかどうかを判断します。問題が検出されると、Console は問題の内容を表示し、ストレージシステムが最高のパフォーマンス、コスト効率、およびベストプラクティスへの準拠を達成するために何を変更する必要があるかを説明します。

主な機能は次のとおりです：

* 日次構成分析
* NetApp ONTAPストレージシステムおよびパートナーストレージプロバイダーに対する自動ベストプラクティス検証
* プロアクティブな可観測性
* 洞察から行動へ




[[analysis-requirements]]
== 分析要件

完全な Cloud Volumes ONTAP システム分析を行うには、link:https://docs.netapp.com/us-en/console-setup-admin/concept-agent-install-options.html#agent-console-deploy["NetApp Consoleエージェントをデプロイします"^]。コンソールエージェント接続により、コンソールはデータ保護やパフォーマンスなど、すべての Cloud Volumes ONTAP システム構成を分析できます。



[[best-practices-and-recommendations-for-cloud-volumes-ontap-systems]]
== Cloud Volumes ONTAP システムのベストプラクティスと推奨事項

NetApp は、ストレージ構成を評価して、ONTAP 構成のベストプラクティスおよび Azure Well-Architected Framework への準拠に関する詳細なビューを提供します。この評価では、改善点や修正点も推奨しています。

適切に設計された分析では、構成をフレームワークの次の柱に分類します：_信頼性_、_セキュリティ_、_運用効率_、_コスト最適化_、および_パフォーマンス効率_。



[[reliability]]
=== 信頼性

信頼性とは、障害が発生した場合でも、ワークロードが意図された機能を正確かつ一貫して実行することを保証するものです。

* *ローカルスナップショットのスケジュール設定*
+
効率的なバックアップと迅速な復元のために、ローカルスナップショットをスケジュール設定しましょう。スナップショットは、ボリュームの瞬時のポイントインタイムイメージです。

* *SSD容量のしきい値*
+
SSDストレージ層の容量は、継続的に使用率が80%を超えないようにしてください。このしきい値を超えると、スループットが低下し、データボリュームが読み取り専用になり、書き込み操作が失敗する可能性があります。





[[security]]
=== セキュリティ

セキュリティは、リスク評価と軽減戦略を通じて、データ、システム、資産を保護することを重視します。

* *AIによる自律型ランサムウェア対策（ARP/AI）*
+
NetApp Autonomous Ransomware Protection with AI（ARP/AI）は、サイバーレジリエンスを強化し、ランサムウェアの脅威からボリュームを保護します。すべてのボリュームでARP/AIを有効にすることをお勧めします。





[[operational-excellence]]
=== 運用の卓越性

運用上の卓越性とは、最高のアーキテクチャとビジネス価値を提供することに重点を置くものです。

* *ボリューム容量使用率のしきい値*
+
NetApp は、ボリューム容量の使用率が継続的に80%を超えないようにすることを推奨します。これは、アプリケーションへのデータの読み書きに影響を与える可能性があります。ボリューム容量の増加は、手動で行うか、ボリュームの自動拡張機能を使用して自動的に行うことができます。

* *キャッシュ関係の書き込みモード*
+
最適なパフォーマンスのために、NetApp はワークロードに最適なキャッシュ関係書き込みモードを推奨します。ライトアラウンドモードは、小さなファイルを扱う読み込み中心のワークロードにおいて優れたパフォーマンスを発揮する一方、ライトバックモードは、大きなファイルを扱う書き込み中心のワークロードにおいて優れたパフォーマンスを発揮します。

* *ONTAPキャッシュボリュームサイズ*
+
NetApp では、最適なサイズを維持し、キャッシュを頻繁にアクセスされる（ホット）データに集中させて最高の効率を実現するために、キャッシュボリュームのボリュームの自動拡張とスクラビングを有効にすることをお勧めします。

* *ONTAPバージョン準拠*
+
完全な互換性、サポート、および新機能へのアクセスを実現するには、最新バージョンの ONTAP にアップグレードしてください。





[[cost-optimization]]
=== コスト最適化

コストの最適化により、コストを低く抑えながらビジネスの価値を最大限に高めることができます。

* *利用されていないSSD容量を特定する*
+
十分に活用されていないSSD容量層は、不必要なコストを発生させている可能性があります。NetApp では、現在の使用容量より20%高い空き容量バッファを維持しながら、SSD層の容量を削減することを推奨します。縮小操作には数時間から数日かかる場合があり、その間、システムは他のファイルシステム操作をサポートしません。

* *データ階層化ポリシー*
+
コールドデータ階層化を有効にすると、コールドデータをSSDストレージ階層から低コストのストレージに移動できます。Azure Blob Storage は、非アクティブなデータの容量層として機能します。



.次の手順
link:improve-configurations-cvo.html["適切に設計されたCloud Volumes ONTAPシステム構成を実装する"]
